class DomainError(Exception): ...


class InvalidUserError(DomainError): ...


class InvalidPostError(DomainError): ...


class InvalidCommentError(DomainError): ...


class PostStatusError(DomainError): ...
